// src/features/code-playground/presentation/templates/angular-template.ts
export const angularTemplate = {
  files: {
    "/src/app/app.component.ts": `import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: \`
    <div class="app">
      <h1>Hello Angular!</h1>
      <p>Start building your component here.</p>
      
      <div class="info">
        <p>✨ You can use:</p>
        <ul>
          <li>Angular Components & Directives</li>
          <li>Services & Dependency Injection</li>
          <li>RxJS Observables</li>
          <li>Angular Forms</li>
        </ul>
      </div>
    </div>
  \`,
  styles: [\`
    .app {
      max-width: 800px;
      margin: 0 auto;
      padding: 2rem;
      background: #2d2d2d;
      border-radius: 8px;
      box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
    }
    
    h1 {
      color: #dd0031;
      margin-top: 0;
    }
    
    .info {
      margin-top: 2rem;
      padding: 1rem;
      background: #1e1e1e;
      border-radius: 4px;
      border-left: 4px solid #dd0031;
    }
    
    ul {
      margin: 0.5rem 0;
      padding-left: 1.5rem;
    }
    
    li {
      margin: 0.5rem 0;
    }
  \`]
})
export class AppComponent {
  title = 'Angular Playground';
}`,
    "/src/main.ts": `import { bootstrapApplication } from '@angular/platform-browser';
import { AppComponent } from './app/app.component';

bootstrapApplication(AppComponent).catch((err) => console.error(err));`,
  },
  dependencies: {
    "@angular/core": "^17.0.0",
    "@angular/platform-browser": "^17.0.0",
    "@angular/platform-browser-dynamic": "^17.0.0",
    rxjs: "^7.8.0",
    tslib: "^2.6.0",
    "zone.js": "^0.14.0",
  },
};

/**
 * Angular starter code for exercise lessons
 */
export const angularExerciseStarter = `import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  template: \`
    <div>
      <h1>Exercise</h1>
      <!-- TODO: Complete the exercise -->
    </div>
  \`
})
export class AppComponent {
  // Your code here
}`;

// src/features/code-playground/presentation/templates/react-template.ts
export const reactTemplate = {
  files: {
    "/App.jsx": `export default function App() {
  return (
    <div className="app">
      <h1>Hello React!</h1>
      <p>Start building your component here.</p>
      
      <div className="info">
        <p>✨ You can use:</p>
        <ul>
          <li>React Hooks (useState, useEffect, etc.)</li>
          <li>JSX syntax</li>
          <li>External packages (install via dependencies)</li>
        </ul>
      </div>
    </div>
  );
}`,
    "/styles.css": `body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, sans-serif;
  padding: 20px;
  background: #1e1e1e;
  color: #e0e0e0;
  margin: 0;
}

.app {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
  background: #2d2d2d;
  border-radius: 8px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.3);
}

h1 {
  color: #61dafb;
  margin-top: 0;
}

.info {
  margin-top: 2rem;
  padding: 1rem;
  background: #1e1e1e;
  border-radius: 4px;
  border-left: 4px solid #61dafb;
}

ul {
  margin: 0.5rem 0;
  padding-left: 1.5rem;
}

li {
  margin: 0.5rem 0;
}`,
  },
  dependencies: {
    react: "^18.2.0",
    "react-dom": "^18.2.0",
  },
};

/**
 * React starter code for exercise lessons
 */
export const reactExerciseStarter = `export default function App() {
  // TODO: Complete the exercise
  
  return (
    <div>
      <h1>Exercise</h1>
    </div>
  );
}`;
